name: Publish to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Godot 4
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip -q -O Godot.zip
          unzip Godot.zip
          mv Godot_v4.4.1-stable_linux.x86_64 godot
          chmod +x godot
      - name: Download Godot 4 export templates
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz -q -O templates.zip
          unzip templates.zip
          mkdir -p /home/runner/.local/share/godot/export_templates/4.4.1.stable/
          mv templates/web_debug.zip /home/runner/.local/share/godot/export_templates/4.4.1.stable/
          mv templates/web_nothreads_debug.zip /home/runner/.local/share/godot/export_templates/4.4.1.stable/
          mv templates/web_release.zip /home/runner/.local/share/godot/export_templates/4.4.1.stable/
          mv templates/web_nothreads_release.zip /home/runner/.local/share/godot/export_templates/4.4.1.stable/
      - name: Export projects
        run: |
          mkdir outputs/
          mkdir outputs/web/
          ./godot --headless --path . --export-release Web
      - name: Publish to Github Pages
        run: |
          touch outputs/web/.nojekyll
          cp -r .git/ outputs/web/
          cd outputs/web
          git add .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Deployment ${{github.sha}}"
          git push -u origin +HEAD:gh-pages
